README.md
package.json
packages/jupyter-chat-extension/README.md
packages/jupyter-chat-extension/package.json
packages/jupyter-chat/package.json

Follow up transferring the project from Quantstack to jupyterlab-contrib

Update the github repo from QuantStack to jupyterlab-contrib

---

README.md
package.json
packages/jupyter-chat-extension/package.json
packages/jupyter-chat-extension/src/handlers/websocket-handler.ts
packages/jupyter-chat-extension/src/index.ts
packages/jupyter-chat-extension/ui-tests/package.json
packages/jupyter-chat/package.json
packages/jupyter-chat/schema/plugin.json
yarn.lock

This change is temporary and should be reverted when the project become an official Jupyter project

 Remove @jupyter namespace from the package name 

---

packages/jupyterlab-collaborative-chat/jupyterlab_collaborative_chat/ychat.py
packages/jupyterlab-collaborative-chat/package.json
packages/jupyterlab-collaborative-chat/schema/commands.json
packages/jupyterlab-collaborative-chat/src/index.ts
packages/jupyterlab-collaborative-chat/src/token.ts
yarn.lock

This PR:
- allows to open a collaborative chat model from an empty file
- adds commands to create and open a chat
- adds menu entry and launcher icon to create a chat

Add commands, menu entry and launcher

---

README.md
package.json
packages/jupyter-chat/package.json
packages/jupyterlab-collaborative-chat/package.json
packages/jupyterlab-collaborative-chat/src/factory.ts
packages/jupyterlab-collaborative-chat/src/index.ts
packages/jupyterlab-collaborative-chat/src/model.ts
packages/jupyterlab-collaborative-chat/src/token.ts
packages/jupyterlab-collaborative-chat/src/widget.ts
packages/jupyterlab-ws-chat/package.json
packages/jupyterlab-ws-chat/src/handlers/websocket-handler.ts
packages/jupyterlab-ws-chat/src/index.ts
yarn.lock

Restore the `@jupyter` namespace in the name of the chat frontend package.
Fixes https://github.com/jupyterlab-contrib/jupyter-chat/issues/7

Add the @jupyter namespace to the NPM chat package

---

packages/jupyter-chat/src/components/chat-messages.tsx
packages/jupyter-chat/src/components/chat.tsx
packages/jupyter-chat/src/components/rendermime-markdown.tsx
packages/jupyter-chat/src/model.ts
packages/jupyter-chat/src/types.ts
packages/jupyterlab-collaborative-chat/jupyterlab_collaborative_chat/ychat.py
packages/jupyterlab-collaborative-chat/src/model.ts
packages/jupyterlab-collaborative-chat/src/ychat.ts
packages/jupyterlab-ws-chat/src/handlers/websocket-handler.ts

This PR (1) improve the YChat document:
- add a `users` section in the document, to avoid duplicating the whole user information for each message
- handle remote update of a message (not from the UI)
- should handle message deletion (not from the UI) 
(2) insert message at the correct position in the flow, using the timestamp of the message

Improve ychat

---

README.md
package.json
packages/jupyter-chat/package.json
packages/jupyterlab-collaborative-chat/.copier-answers.yml
packages/jupyterlab-collaborative-chat/README.md
packages/jupyterlab-collaborative-chat/package.json
packages/jupyterlab-ws-chat/README.md
packages/jupyterlab-ws-chat/package.json

Update the github organization from 'jupyterlab-contrib' to 'jupyterlab'

---

packages/jupyter-chat/src/components/chat-input.tsx
packages/jupyter-chat/src/components/chat-messages.tsx
packages/jupyter-chat/src/types.ts
packages/jupyterlab-collaborative-chat/jupyterlab_collaborative_chat/ychat.py
packages/jupyterlab-collaborative-chat/src/model.ts
packages/jupyterlab-collaborative-chat/ui-tests/tests/jupyterlab_collaborative_chat.spec.ts

Fix #23 
With this PR the time of the message is updated with the time of the server, when the message is added in the collaborative document. This increases reliability of the timestamp by using a unique source.
It also add a `*` and a tooltip on the time if it has not been updated, using a new `raw_time` key in `IChatMessage`.

Use the server time in collaborative chat

---

packages/jupyter-chat/src/components/chat-input.tsx
packages/jupyter-chat/src/components/chat-messages.tsx
packages/jupyter-chat/src/components/chat.tsx

This PR fixes the time displayed in the header of the message.
The message can have a different timestamp computed on server side, but before this PR the representation of this timestamp was cached using the message ID, so it did not change on the chat UI.
This PR caches the string representation using the timestamp instead of message ID.
It also moves the react state `input` in the input widget (instead of the chat widget), to avoid reloading all the messages when the input changes.

Fix message datetime

---

packages/jupyter-chat/src/__tests__/model.spec.ts
packages/jupyter-chat/src/components/chat.tsx
packages/jupyter-chat/src/model.ts
packages/jupyter-chat/src/types.ts
packages/jupyterlab-collaborative-chat/jupyterlab_collaborative_chat/ychat.py
packages/jupyterlab-collaborative-chat/src/model.ts
packages/jupyterlab-collaborative-chat/src/ychat.ts
packages/jupyterlab-collaborative-chat/ui-tests/tests/jupyterlab_collaborative_chat.spec.ts
packages/jupyterlab-ws-chat/src/handlers/websocket-handler.ts

This PR aims to use a list of messages in `YChat` document, instead of a Map.
Fixes #25
Before this PR, the messages order was handled in the chat component itself.
With this PR, the messages list is handled in the model, and used by the chat component. It adds some function to insert or delete messages with index.
The collaborative chat document now saves messages in a list and is responsible for the message order. That way the order is computed only once, when a message is added, server side. It make use of the insert/delete functions of the model to set the order in front end side.

Messages as a list in collaborative chat document

---

README.md

Add a screenshot to the README, so folks landing on the repo have a better idea of what the chat looks like.

Add screenshot to the README

---

packages/jupyter-chat/src/components/chat.tsx
packages/jupyterlab-collaborative-chat/schema/factory.json
packages/jupyterlab-collaborative-chat/src/factory.ts
packages/jupyterlab-collaborative-chat/src/index.ts
packages/jupyterlab-collaborative-chat/src/token.ts
packages/jupyterlab-collaborative-chat/src/widget.tsx
packages/jupyterlab-collaborative-chat/ui-tests/tests/jupyterlab_collaborative_chat.spec.ts

This PR adds the panel tracker to a factory token, the token returned by the plugin which crate the document factories (model and widget).
There is also some refactoring for a better readability.

Add the panel tracker to the chat factory token

---

packages/jupyterlab-ws-chat/jupyterlab_ws_chat/handlers.py
packages/jupyterlab-ws-chat/jupyterlab_ws_chat/models.py
packages/jupyterlab-ws-chat/pyproject.toml

Looks like `langchain` is currently used as a proxy for importing `pydantic_v1`.
So we can probably depend on `pydantic` directly and update the imports, to avoid having to depend on `langchain`.

Depend on `pydantic` directly instead of `langchain`

---

packages/jupyter-chat/src/components/chat-messages.tsx
packages/jupyter-chat/src/model.ts
packages/jupyterlab-collaborative-chat/jupyterlab_collaborative_chat/ychat.py
packages/jupyterlab-collaborative-chat/src/model.ts
packages/jupyterlab-collaborative-chat/src/ychat.ts
packages/jupyterlab-collaborative-chat/ui-tests/tests/jupyterlab_collaborative_chat.spec.ts
packages/jupyterlab-ws-chat/src/handlers/websocket-handler.ts

This PR store the last read message in the local storage, to mark new messages only as unread when opening a chat.
To handle it properly, it adds an ID to the chat, which is stored as metadata in the collaborative chat.
Therefore this PR change the ychat definition to handle metadata.
Related to https://github.com/jupyterlab/jupyter-chat/pull/43.
Currently it only saves the date of the last message read, which means that if some previous message were unread, they will be considered as read when reopening the chat.

Add metadata to ychat, id to model and store last unread in localStorage

---

packages/jupyter-chat/src/components/chat-messages.tsx
packages/jupyter-chat/src/components/scroll-container.tsx
packages/jupyter-chat/src/icons.ts
packages/jupyter-chat/style/icons/read.svg
packages/jupyterlab-collaborative-chat/schema/chat-panel.json
packages/jupyterlab-collaborative-chat/src/index.ts
packages/jupyterlab-collaborative-chat/src/token.ts
packages/jupyterlab-collaborative-chat/src/widget.tsx
packages/jupyterlab-collaborative-chat/ui-tests/tests/jupyterlab_collaborative_chat.spec.ts

- adds 'mark read' buttons in collaborative chat
- avoid scrolling to the end of the chat when showing the chat, but scroll to the first unread at startup

Buttons to mark chat as read

---

package.json
packages/jupyterlab-collaborative-chat/ui-tests/package.json
packages/jupyterlab-ws-chat/ui-tests/package.json

This PR should prevent dependabot from using yarn 4, and change the whole dependencies in `yarn.lock`.
See https://github.com/jupyterlab/extension-template/pull/79 for more information.

Prevent dependabot from using yarn 4

---

packages/jupyter-chat/src/components/chat-input.tsx
packages/jupyter-chat/src/components/chat.tsx
packages/jupyter-chat/src/index.ts
packages/jupyter-chat/src/registry.ts
packages/jupyter-chat/src/types.ts
packages/jupyterlab-collaborative-chat/src/factory.ts
packages/jupyterlab-collaborative-chat/src/index.ts
packages/jupyterlab-collaborative-chat/src/widget.tsx
packages/jupyterlab-collaborative-chat/ui-tests/tests/autocompletion.spec.ts
packages/jupyterlab-collaborative-chat/ui-tests/tests/jupyterlab_collaborative_chat.spec.ts
packages/jupyterlab-ws-chat/src/index.ts

This PR adds autocomplete commands to the chat component, using a registry.
It is strongly inspired by the PR made by @dlqqq in `jupyter-ai` https://github.com/jupyterlab/jupyter-ai/pull/810
Fixes https://github.com/jupyterlab/jupyter-chat/issues/51
If some autocomplete commands are provided, a list of commands will open if the first character match a specific string.
The logic is as following:
- an extension like `jupyterlab-collaborativ-chat` provides a registry for autocomplete commands, using a token.
- an extension relying on `jupyterlab-collaborativ-chat` (like possibly `jupyter-ai`) will be able to register some autocomplete commands for its own use.
The 2 extensions (collaborative and websocket chat) provide the token in a new plugin.
cc @jtpio

Autocomplete commands

---

packages/jupyter-chat/src/components/chat-input.tsx
packages/jupyter-chat/src/model.ts
packages/jupyterlab-collaborative-chat/src/token.ts
packages/jupyterlab-collaborative-chat/src/widget.tsx
python/jupyterlab-collaborative-chat/schema/commands.json
python/jupyterlab-collaborative-chat/src/index.ts
python/jupyterlab-ws-chat/schema/chat.json
python/jupyterlab-ws-chat/src/index.ts

This PR adds a shortcut in the extensions to focus on the chat input.
It's mostly a refactoring of https://github.com/jupyterlab/jupyter-ai/pull/876
In the case of the collaborative chat, where several chat can be opened at the same time, the focus goes to the "current" chat in the main area (the current is the last active one).
Related to https://github.com/jupyterlab/jupyter-ai/issues/862

Shortcut to focus on the chat input

---

python/jupyterlab-collaborative-chat/package.json

Bundle *@jupyter/chat* as a shared package in *jupyter-collaborative-chat-extension*, to properly provide the `IAutocompletionRegistry` token.

Bundle @jupyter/chat

---

binder/environment.yml
packages/jupyterlab-collaborative-chat/package.json
python/jupyterlab-collaborative-chat/package.json
python/jupyterlab-collaborative-chat/pyproject.toml
yarn.lock

This PR update the jupyter_collaboration dependency to 2.1.4.
This allows using the awareness on the server side, following https://github.com/jupyterlab/jupyter-collaboration/pull/376

Update jupyter_collaboration dependency

---

packages/jupyter-chat/src/components/rendermime-markdown.tsx

Porting of https://github.com/jupyterlab/jupyter-ai/pull/1068

Allow `$` to literally denote quantities of USD in chat

---

packages/jupyter-chat/src/components/code-blocks/code-toolbar.tsx
packages/jupyter-chat/src/components/mui-extras/tooltipped-icon-button.tsx

Port https://github.com/jupyterlab/jupyter-ai/pull/1072 to improve padding around code toolbar buttons.

Improve padding around code toolbar buttons

---

packages/jupyter-chat/src/components/rendermime-markdown.tsx

Porting https://github.com/jupyterlab/jupyter-ai/pull/1094
This PR reverts the changes of #95.
> Users can still use $ to delimit inline math, and must double-escape $ symbols to use them literally (`\\$`). This is aligned with JupyterLab's rendering behavior.

Revert 'Allow `$` to literally denote quantities of USD in chat' (#95)

---

packages/jupyter-chat/src/components/chat-input.tsx
packages/jupyter-chat/src/components/input/cancel-button.tsx

Fixes #118 
Port https://github.com/jupyterlab/jupyter-ai/pull/946
**EDIT**
- prevent sending empty message (only whitespace) with keyboard and button
- remove condition on 'cancel' button to disable it

Prevent sending empty message

---

python/jupyterlab-chat/jupyterlab_chat/models.py
python/jupyterlab-chat/jupyterlab_chat/tests/test_ychat.py
python/jupyterlab-chat/jupyterlab_chat/ychat.py

- Fixes #120.
- **EDIT**: also fixes #114.
- Adds a lookup table in YChat, to keep find message index from its ID.
- Adds a `NewMessage` type, containing only the message body and the sender (timestamp and id are generated before inserting the message.
- Removes the `set_message()`, since `add_message()` and `update_message()` do not have the same parameter type anymore.

Remove need for message index in YChat API methods

---

packages/jupyterlab-chat/package.json
packages/jupyterlab-chat/src/widget.tsx
packages/jupyterlab-chat/src/ychat.ts
python/jupyterlab-chat/package.json
python/jupyterlab-chat/pyproject.toml
python/jupyterlab-chat/src/index.ts
yarn.lock

Update dependencies:
- `jupyter_collaboration >= 3` (python and javascript)
- `@jupyter/ydoc>2` (javascript)

Upgrade to Jupyter Collaboration 3

---

.github/workflows/build.yml
python/jupyterlab-chat/jupyterlab_chat/models.py

- Closes #134.
- Adds a GitHub job for running Python unit tests on Python 3.9. I've verified that this job catches the original issue, ensuring it will not happen again. See below for more details.
- Fixes Python 3.9 support for `jupyterlab_chat`.

Fix support for Python 3.9

---

.github/workflows/build.yml
.github/workflows/check-release.yml

To fix the currently failing CI:
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
```

Update to `actions/upload-artifact@v4` and `actions/download-artifact@v4`

---

packages/jupyter-chat/src/components/chat-input.tsx

Fixes #155 
This PR prevent propagating the up and down arrow event to the `Autocomplete` component if the autocompletion is not opened.
It is weird that it is not handled by material UI itself, maybe there is a better solution.

Allow use of up and down arrow in chat input

---

packages/jupyter-chat/src/chat-commands/types.ts
packages/jupyter-chat/src/components/input/use-chat-commands.tsx
packages/jupyterlab-chat/style/base.css
python/jupyterlab-chat/src/chat-commands/providers/emoji.ts

- Closes #175 
Issue: [Issue-175](https://github.com/jupyterlab/jupyter-chat/issues/175)
**Problem Statement**
The new chat commands menu needs to show icons & descriptions. The ChatCommand type will probably need updates accordingly.
**Expected behavior**
Updated UI showing icons & descriptions in menu of chat commands
**Testing**
* Tested in local environment

Add icons & descriptions to chat commands menu

---

packages/jupyter-chat/style/chat.css
packages/jupyterlab-chat/style/base.css

This PR moves the CSS rules of chat commands from `jupyterlab-chat` to `@jupyter/chat` (where they are defined).
`@jupyter/chat` can be used as a frontend extension that does not depends on `jupyterlab-chat`.
Therefore, the CSS rules should be defined in `@jupyter/chat`.

Move the CSS rules of chat commands in @jupyter/chat

---

packages/jupyter-chat/src/components/code-blocks/copy-button.tsx

- Closes #186
**Problem Statement**
The "Copy to Clipboard" button fails to function when the JupyterLab server is accessed over HTTP (insecure context). Clipboard functionality requires a secure context (HTTPS or localhost), and when the server runs on HTTP, the copy action is disabled. This can cause confusion for users who may expect the button to work even in insecure contexts. To improve the user experience and minimize confusion, the copy button should be disabled when the server is served over HTTP, with a tooltip explaining that copying requires a secure context.
**Changes Made**
- Updated the `useCopy` hook to include an additional boolean parameter that controls the button's enabled/disabled state.
- Added a new status, `Disabled`, to indicate the copy status along with an …

Disable the copy button in insecure contexts

---

packages/jupyter-chat/src/components/input/use-chat-commands.tsx

This PR deletes the trailing hyphen in the autocomplete suggestion (chat commands), if the description is empty.
Example:

Fix the trailing hyphen in completion without description

---

packages/jupyterlab-chat/src/model.ts
python/jupyterlab-chat/jupyterlab_chat/models.py

Follow up #148.
The python `Message` model was missing the `attachments` property, which led to error when trying to cast some message dict to `Message` objects:
```bash
TypeError: Message.__init__() got an unexpected keyword argument 'attachments'
```
Should fixes issues [2] and [4] in https://github.com/jupyterlab/jupyter-ai/issues/1293

Fix the attachments on message edition and on python Message model

---

packages/jupyterlab-chat/src/factory.ts

Follow up #198.
Creates the toolbar registry when creating the widget, instead of creating it in the constructor of the widget factory.
Before this PR, the input toolbar registry was shared between all the main area widgets. This does not allow adding custom buttons, including for example the chat model. The button was added by the first opened chat, including its options.

Fix the toolbar registry for main area chat

---

scripts/bump_version.py

Follow up #196 to fix the version of the `_version.py` file in python extension when bumping to a specific value (e.g `0.10.0`)

Fix _version.py file version bump

---

packages/jupyterlab-chat-extension/src/chat-commands/providers/user-mention.tsx
ui-tests/tests/user-mention.spec.ts

Fixes #209 by comparing only lower case string.

Fix case-sensitivity in user mention commands

---

packages/jupyter-chat/src/components/chat-messages.tsx
packages/jupyter-chat/src/types.ts
python/jupyterlab-chat/jupyterlab_chat/models.py

* Fixes #117
* Add optional `bot` bool to `User` and `IUser` models
* Allow users to delete messages if sender is a bot (`sender.bot` is set)
Any user can delete a message if sender is a bot.
Given chat below
```
{
"messages": [
{
"body": "test",
"type": "msg",
"id": "f5f082f6-6d8b-40cb-bd0c-19166edc7c66",
"time": 1744836704.329035,
"raw_time": false,
"sender": "853888eb11294e9696a37acf577b8b7c"
},
{
"raw_time": false,
"time": 1744836766.093413,
"type": "msg",
"sender": "3931ab15829e49cbb11f2cad35bea0ab",
"body": "test",
"id": "6bc81764-6271-4ad1-a7a8-bffec332a21a"
}
],
"users": {
"853888eb11294e9696a37acf577b8b7c": {
"avatar_url": null,
"display_name": "Anonymous Euporie",
"color": "var(--jp-collaborator-color3)",
"username": "853888eb11294e9696a37acf577b8b7c",
"name": "Anonymous …
```

Allow Users to delete messages if sender is a bot, add optional `bot` bool to user models

---

packages/jupyter-chat/package.json
packages/jupyter-chat/src/components/chat-messages.tsx
packages/jupyter-chat/src/input-model.ts
packages/jupyter-chat/src/model.ts
packages/jupyterlab-chat/src/model.ts
ui-tests/tests/ui-config.spec.ts
yarn.lock

This PR improves the handling of the writers, by sending also the message being edited.
Related to https://github.com/jupyterlab/jupyter-chat/issues/202, see https://github.com/jupyterlab/jupyter-chat/issues/202#issuecomment-2785824848 for context (only the last change was required by #202).
- when editing a message, the input model of the message edition is added to the chat model ~=> only one message can be edited at the same time~
- jupyterlab-chat also listen to the message edition to update the writer list
- the writer list can optionally contain a message ID if this is a message edition

Display user writing notification when editing a message

---

packages/jupyter-chat/package.json
packages/jupyter-chat/src/active-cell-manager.ts
packages/jupyter-chat/src/components/input/buttons/send-button.tsx
packages/jupyter-chat/src/selection-watcher.ts
packages/jupyterlab-chat-extension/package.json
packages/jupyterlab-chat-extension/src/index.ts
ui-tests/tests/send-message.spec.ts
yarn.lock

This PR add code highlighting when  it is attached from a cell or a selection.
The language is added to the markdown code block when it is available.
- Code attached from a cell
Get the language from the `defaultKernelLanguage` of the Notebook metadata. If not defined, there is no syntax highlighting.
- Code attached from a selection
Retrieve the `DocumentWidget` mimetype from its editor [model](https://github.com/jupyterlab/jupyterlab/blob/1f18828225e5e16c569dcb810eb4c6137cd33d9b/packages/codeeditor/src/editor.ts#L144), and convert it to a language using the [`EditorLanguageRegistry`](https://github.com/jupyterlab/jupyterlab/blob/1f18828225e5e16c569dcb810eb4c6137cd33d9b/packages/codemirror/src/language.ts#L61). 
If the mimetype cannot be converted to a language,there is no syntax …

Code highlight in message

---

docs/jupyter-chat-example/src/index.ts
packages/jupyter-chat/src/components/input/chat-input.tsx
packages/jupyter-chat/src/components/input/use-chat-commands.tsx
packages/jupyter-chat/src/input-model.ts
packages/jupyter-chat/src/types.ts
packages/jupyter-chat/src/utils.ts
packages/jupyterlab-chat-extension/src/chat-commands/providers/user-mention.tsx
packages/jupyterlab-chat/src/model.ts
packages/jupyterlab-chat/src/ychat.ts
python/jupyterlab-chat/jupyterlab_chat/models.py
python/jupyterlab-chat/jupyterlab_chat/tests/test_ychat.py

- Closes #241
This PR fixes each of the small bugs reported in #241. The commit history addresses each in the order they appear in #241.
The most notable changes are:
1. The `user.mention_name` property has been made consistent across the frontend & backend. It is now computed using the same procedure and is always defined in the `LabChatModel`.
2. The `inputModel.currentWord` property has been modified to allow for spaces escaped with a preceding backslash `\` in the current word. This allows commands to contain spaces, allowing `@file` in JAI to accept file paths that contain spaces.

Fix v0.14.0 bugs

---

packages/jupyter-chat/src/types.ts
packages/jupyterlab-chat-extension/src/chat-commands/providers/user-mention.tsx
packages/jupyterlab-chat/src/model.ts

- Closes #245.
Makes `user.mention_name` optional in the frontend. See discussion in #245 for context.

Make `user.mention_name` optional in frontend

---

packages/jupyterlab-chat-extension/src/index.ts

* Fixes #239 
* Added `startup` parameter to `openChat` command to distinguish startup restoration from intentional file opening
* Updated layout restorer to pass `startup: true` during workspace restoration
* Modified error handling to log warning instead of showing error dialog when chat path not found during startup restoration
During startup restoration, console warnings is logged (visible in browser dev tools) instead of showing error dialog when chat path is not found. 
Before this PR:
After this PR:

Log warning instead of showing error dialog when chat file path not found during startup restoration

---

packages/jupyterlab-chat-extension/src/index.ts

* Fixes #256
> In JupyterLab, the launcher closes when you create a new document on widget from it. Basically, the new doc replaces the launcher. In Jupyter Chat, when you create a chat file from the launcher, the launcher stays open. 
Returns docmanager widget from createChat/openChat commands to ensure proper launcher disposal.
New chats created in main area replace launcher.
None.
Before this PR: 
After this PR:

Return docmanager widget from createChat/openChat commands to ensure launcher disposal

---

packages/jupyter-chat/src/components/messages/messages.tsx
packages/jupyter-chat/src/widgets/chat-widget.tsx

Previously, clicking anywhere in the chat panel forced focus onto the input (`this.node.onclick = () => this.model.input.focus();`). This made it difficult to select or copy text from the chat history, since every click redirected focus.
Now we check if the user has selected text input loses focus, click on `button`,` interactive elements`, `<details>`, `<summary>` and else work like before
https://github.com/user-attachments/assets/4f9b995e-01f2-4b29-be33-ed6597782000
Closes #267

Fix chat focus behavior to allow copy/paste from messages
